# List Products & Measurements
First we will pull in the modules as described in [Getting Started](Getting Started.ipynb).

In [11]:
%matplotlib inline
import datacube
import pandas
pandas.set_option('display.max_colwidth', 200)
pandas.set_option('display.max_rows', None)

In [12]:
dc = datacube.Datacube()

## List Products
We can get all the products in datacube as a `pandas DataFrame`:

In [13]:
products = dc.list_products()

In [14]:
products.columns.tolist()

['name',
 'description',
 'platform',
 'lon',
 'product_type',
 'time',
 'label',
 'gqa_abs_xy',
 'region_code',
 'gqa',
 'sat_path',
 'lat',
 'gqa_ref_source',
 'gqa_final_gcp_count',
 'gqa_cep90',
 'gqa_error_message',
 'format',
 'gqa_mean_xy',
 'gqa_abs_iterative_mean_xy',
 'creation_time',
 'orbit',
 'gqa_iterative_stddev_xy',
 'sat_row',
 'instrument',
 'gsi',
 'gqa_iterative_mean_xy',
 'gqa_stddev_xy',
 'ancillary_quality',
 'crs',
 'resolution',
 'tile_size',
 'spatial_dimensions']

We don't want to see most of these columns, so we will limit the `DataFrame` to just a few, and show the rows with a `product_type` of `nbar`:

In [15]:
display_columns = ['name', 'description', 'platform', 'instrument', 'crs', 'resolution']
nbar_products = products[display_columns].dropna()
#nbar_products = products[products['product_type'] == 'nbar'][display_columns].dropna()
nbar_products

,name,description,platform,instrument,crs,resolution
id,,,,,,
36,bom_rainfall_grids,Interpolated Rain Gauge Precipitation 1-Day Australia 5km Gridded,BoM,rain gauge,EPSG:4326,"(-0.05, 0.05)"
32,dsm1sv10,DSM 1sec Version 1.0,SRTM,SIR,EPSG:4326,"(-0.00027777777778, 0.00027777777778)"
53,gamma_ray,The 2015 radiometric or gamma-ray grid of Australia,aircraft,gamma_ray spectrometer,"GEOGCS[""GEOCENTRIC DATUM of AUSTRALIA"",DATUM[""GDA94"",SPHEROID[""GRS80"",6378137,298.257222101]],PRIMEM[""Greenwich"",0],UNIT[""degree"",0.0174532925199433]]","(-0.001, 0.001)"
69,ls5_fc_albers,"Landsat 5 Fractional Cover 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_5,TM,EPSG:3577,"(-25, 25)"
6,ls5_nbar_albers,"Landsat 5 Surface Reflectance NBAR 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_5,TM,EPSG:3577,"(-25, 25)"
26,ls5_nbart_albers,"Landsat 5 Surface Reflectance NBART 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_5,TM,EPSG:3577,"(-25, 25)"
83,ls5_nbart_geomedian_annual,"Surface Reflectance Geometric Median 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_5,TM,EPSG:3577,"(-25, 25)"
23,ls5_pq_albers,"Landsat 5 Pixel Quality 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_5,TM,EPSG:3577,"(-25, 25)"
70,ls7_fc_albers,"Landsat 7 Fractional Cover 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_7,ETM,EPSG:3577,"(-25, 25)"
21,ls7_nbar_albers,"Landsat 7 Surface Reflectance NBAR 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_7,ETM,EPSG:3577,"(-25, 25)"
29,ls7_nbart_albers,"Landsat 7 Surface Reflectance NBART 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_7,ETM,EPSG:3577,"(-25, 25)"
82,ls7_nbart_geomedian_annual,"Surface Reflectance Geometric Median 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_7,ETM,EPSG:3577,"(-25, 25)"
22,ls7_pq_albers,"Landsat 7 Pixel Quality 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_7,ETM,EPSG:3577,"(-25, 25)"
98,ls8_barest_earth_mosaic,"Landsat-8 Barest Earth pixel composite mosaic 25 metre, 25km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI,EPSG:3577,"(-25, 25)"
71,ls8_fc_albers,"Landsat 8 Fractional Cover 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI_TIRS,EPSG:3577,"(-25, 25)"
19,ls8_nbar_albers,"Landsat 8 Surface Reflectance NBAR 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI_TIRS,EPSG:3577,"(-25, 25)"
60,ls8_nbar_oli_albers,"Landsat 8 Surface Reflectance NBAR 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI,EPSG:3577,"(-25, 25)"
28,ls8_nbart_albers,"Landsat 8 Surface Relfectance NBART 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI_TIRS,EPSG:3577,"(-25, 25)"
81,ls8_nbart_geomedian_annual,"Surface Reflectance Geometric Median 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI,EPSG:3577,"(-25, 25)"
61,ls8_nbart_oli_albers,"Landsat 8 Surface Relfectance NBART 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI,EPSG:3577,"(-25, 25)"
20,ls8_pq_albers,"Landsat 8 Pixel Quality 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI_TIRS,EPSG:3577,"(-25, 25)"
80,ls8_pq_oli_albers,"Landsat 8 Pixel Quality 25 metre, 100km tile, Australian Albers Equal Area projection (EPSG:3577)",LANDSAT_8,OLI,EPSG:3577,"(-25, 25)"
56,srtm_dem1sv1_0,DEM 1sec Version 1.0,Space Shuttle Endeavour,SIR,EPSG:4326,"(-0.00027777777778, 0.00027777777778)"
97,wofs_annual_summary,Water Observations from Space Annual Statistics,"LANDSAT_5,LANDSAT_7,LANDSAT_8","TM,ETM,OLI",EPSG:3577,"(-25, 25)"
85,wofs_filtered_summary,Water Observations from Space Statistics confidence filtered,"LANDSAT_5,LANDSAT_7,LANDSAT_8","TM,ETM+,OLI",EPSG:3577,"(-25, 25)"
84,wofs_summary,Water Observations from Space Statistics,"LANDSAT_5,LANDSAT_7,LANDSAT_8","TM,ETM+,OLI",EPSG:3577,"(-25, 25)"

## List Measurements

In [25]:
measurements = dc.list_measurements()

In [26]:
measurements.columns.tolist()

['aliases',
 'dtype',
 'flags_definition',
 'name',
 'nodata',
 'spectral_definition',
 'units']

In [27]:
display_columns = ['units', 'nodata', 'aliases']

We can look at the measurements for just one product, such as `ls5_nbar_albers`:

In [29]:
measurements[display_columns].loc['ls5_nbar_albers']

            units nodata          aliases
measurement
blue            1   -999   [band_1, blue]
green           1   -999  [band_2, green]
red             1   -999    [band_3, red]
nir             1   -999    [band_4, nir]
swir1           1   -999  [band_5, swir1]
swir2           1   -999  [band_7, swir2]

Or we can look at a list of them:

In [32]:
product_list = nbar_products.name.tolist()
product_list

['ls5_nbar_albers',
 'ls7_nbar_albers',
 'ls8_nbar_albers',
 'ls8_nbar_oli_albers']

In [33]:
measurements[display_columns].loc[product_list]

                                    units nodata                    aliases
product             measurement
ls5_nbar_albers     blue                1   -999             [band_1, blue]
                    green               1   -999            [band_2, green]
                    red                 1   -999              [band_3, red]
                    nir                 1   -999              [band_4, nir]
                    swir1               1   -999            [band_5, swir1]
                    swir2               1   -999            [band_7, swir2]
ls7_nbar_albers     blue                1   -999             [band_1, blue]
                    green               1   -999            [band_2, green]
                    red                 1   -999              [band_3, red]
                    nir                 1   -999              [band_4, nir]
                    swir1               1   -999            [band_5, swir1]
                    swir2               1   -999            [band_7, swir2]
ls8_nbar_albers     coastal_aerosol     1   -999  [band_1, coastal_aerosol]
                    blue                1   -999             [band_2, blue]
                    green               1   -999            [band_3, green]
                    red                 1   -999              [band_4, red]
                    nir                 1   -999              [band_5, nir]
                    swir1               1   -999            [band_6, swir1]
                    swir2               1   -999            [band_7, swir2]
ls8_nbar_oli_albers coastal_aerosol     1   -999  [band_1, coastal_aerosol]
                    blue                1   -999             [band_2, blue]
                    green               1   -999            [band_3, green]
                    red                 1   -999              [band_4, red]
                    nir                 1   -999              [band_5, nir]
                    swir1               1   -999            [band_6, swir1]
                    swir2               1   -999            [band_7, swir2]