In [ ]:
%matplotlib inline
import warnings; warnings.simplefilter('ignore')

import fnmatch
import os
import pandas as pd
import geopandas as gpd

#from datacube_stats.statistics import GeoMedian
#from datacube.helpers import ga_pq_fuser
#from datacube.storage import masking
#from datacube.helpers import write_geotiff
import xarray as xr

#get the DEA version of the plotting functions
import sys
sys.path.append(os.path.abspath('/g/data/r78/DPIPWE_lm/dea-notebooks/10_Scripts'))
#import DEAPlotting
#import DEADataHandling

In [2]:
bm = xr.open_dataset('/g/data/r78/DPIPWE_lm/test_burn_mapping/output_data/2017_2018/BurnScarMap_2017_2018_10_-48_old.nc')

In [4]:
bm

<xarray.Dataset>
Dimensions:      (x: 4000, y: 4000)
Coordinates:
  * y            (y) float64 -4.6e+06 -4.6e+06 -4.6e+06 ... -4.5e+06 -4.5e+06
  * x            (x) float64 1e+06 1e+06 1e+06 1e+06 ... 1.1e+06 1.1e+06 1.1e+06
Data variables:
    StartDate    (y, x) float64 ...
    Duration     (y, x) int16 ...
    Severity     (y, x) float32 ...
    Severe       (y, x) int8 ...
    Moderate     (y, x) int8 ...
    Corroborate  (y, x) int8 ...
Attributes:
    crs:      EPSG:3577

In [5]:
bm.StartDate

<xarray.DataArray 'StartDate' (y: 4000, x: 4000)>
[16000000 values with dtype=float64]
Coordinates:
  * y        (y) float64 -4.6e+06 -4.6e+06 -4.6e+06 ... -4.5e+06 -4.5e+06
  * x        (x) float64 1e+06 1e+06 1e+06 1e+06 ... 1.1e+06 1.1e+06 1.1e+06

In [6]:
tempDF = bm.to_dataframe()

In [7]:
tempDF

                         StartDate  Duration  Severity  Severe  Moderate  \
x         y
1000012.5 -4599987.5  1.522368e+18        63   2.07602       1         1
          -4599962.5           NaN         0   0.00000       0         0
          -4599937.5           NaN         0   0.00000       0         0
          -4599912.5           NaN         0   0.00000       0         0
          -4599887.5           NaN         0   0.00000       0         0
          -4599862.5           NaN         0   0.00000       0         0
          -4599837.5           NaN         0   0.00000       0         0
          -4599812.5           NaN         0   0.00000       0         0
          -4599787.5           NaN         0   0.00000       0         0
          -4599762.5           NaN         0   0.00000       0         0
          -4599737.5           NaN         0   0.00000       0         0
          -4599712.5           NaN         0   0.00000       0         0
          -4599687.5           NaN         0   0.00000       0         0
          -4599662.5           NaN         0   0.00000       0         0
          -4599637.5           NaN         0   0.00000       0         0
          -4599612.5           NaN         0   0.00000       0         0
          -4599587.5           NaN         0   0.00000       0         0
          -4599562.5           NaN         0   0.00000       0         0
          -4599537.5           NaN         0   0.00000       0         0
          -4599512.5           NaN         0   0.00000       0         0
          -4599487.5           NaN         0   0.00000       0         0
          -4599462.5           NaN         0   0.00000       0         0
          -4599437.5           NaN         0   0.00000       0         0
          -4599412.5           NaN         0   0.00000       0         0
          -4599387.5           NaN         0   0.00000       0         0
          -4599362.5           NaN         0   0.00000       0         0
          -4599337.5           NaN         0   0.00000       0         0
          -4599312.5           NaN         0   0.00000       0         0
          -4599287.5           NaN         0   0.00000       0         0
          -4599262.5           NaN         0   0.00000       0         0
...                            ...       ...       ...     ...       ...
1099987.5 -4500737.5           NaN         0   0.00000       0         0
          -4500712.5           NaN         0   0.00000       0         0
          -4500687.5           NaN         0   0.00000       0         0
          -4500662.5           NaN         0   0.00000       0         0
          -4500637.5           NaN         0   0.00000       0         0
          -4500612.5           NaN         0   0.00000       0         0
          -4500587.5           NaN         0   0.00000       0         0
          -4500562.5           NaN         0   0.00000       0         0
          -4500537.5           NaN         0   0.00000       0         0
          -4500512.5           NaN         0   0.00000       0         0
          -4500487.5           NaN         0   0.00000       0         0
          -4500462.5           NaN         0   0.00000       0         0
          -4500437.5           NaN         0   0.00000       0         0
          -4500412.5           NaN         0   0.00000       0         0
          -4500387.5           NaN         0   0.00000       0         0
          -4500362.5           NaN         0   0.00000       0         0
          -4500337.5           NaN         0   0.00000       0         0
          -4500312.5           NaN         0   0.00000       0         0
          -4500287.5           NaN         0   0.00000       0         0
          -4500262.5           NaN         0   0.00000       0         0
          -4500237.5           NaN         0   0.00000       0         0
          -4500212.5           NaN         0   0.00000       0         0
          -4500187.5           NaN         0   0.00000       0         0
          -4500162.5           NaN         0   0.00000       0         0
          -4500137.5           NaN         0   0.00000       0         0
          -4500112.5           NaN         0   0.00000       0         0
          -4500087.5           NaN         0   0.00000       0         0
          -4500062.5           NaN         0   0.00000       0         0
          -4500037.5           NaN         0   0.00000       0         0
          -4500012.5           NaN         0   0.00000       0         0

                      Corroborate
x         y
1000012.5 -4599987.5            0
          -4599962.5            0
          -4599937.5            0
          -4599912.5            0
          -4599887.5            0
          -4599862.5            0
          -4599837.5            0
          -4599812.5            0
          -4599787.5            0
          -4599762.5            0
          -4599737.5            0
          -4599712.5            0
          -4599687.5            0
          -4599662.5            0
          -4599637.5            0
          -4599612.5            0
          -4599587.5            0
          -4599562.5            0
          -4599537.5            0
          -4599512.5            0
          -4599487.5            0
          -4599462.5            0
          -4599437.5            0
          -4599412.5            0
          -4599387.5            0
          -4599362.5            0
          -4599337.5            0
          -4599312.5            0
          -4599287.5            0
          -4599262.5            0
...                           ...
1099987.5 -4500737.5            0
          -4500712.5            0
          -4500687.5            0
          -4500662.5            0
          -4500637.5            0
          -4500612.5            0
          -4500587.5            0
          -4500562.5            0
          -4500537.5            0
          -4500512.5            0
          -4500487.5            0
          -4500462.5            0
          -4500437.5            0
          -4500412.5            0
          -4500387.5            0
          -4500362.5            0
          -4500337.5            0
          -4500312.5            0
          -4500287.5            0
          -4500262.5            0
          -4500237.5            0
          -4500212.5            0
          -4500187.5            0
          -4500162.5            0
          -4500137.5            0
          -4500112.5            0
          -4500087.5            0
          -4500062.5            0
          -4500037.5            0
          -4500012.5            0

[16000000 rows x 6 columns]

In [10]:
tempDF['StartDate'] = pd.to_datetime(tempDF['StartDate'], format=None)

In [11]:
tempDF['month'] = pd.DatetimeIndex(tempDF['StartDate']).month

In [12]:
print(tempDF['month'])

x          y
1000012.5  -4599987.5    3.0
           -4599962.5    NaN
           -4599937.5    NaN
           -4599912.5    NaN
           -4599887.5    NaN
           -4599862.5    NaN
           -4599837.5    NaN
           -4599812.5    NaN
           -4599787.5    NaN
           -4599762.5    NaN
           -4599737.5    NaN
           -4599712.5    NaN
           -4599687.5    NaN
           -4599662.5    NaN
           -4599637.5    NaN
           -4599612.5    NaN
           -4599587.5    NaN
           -4599562.5    NaN
           -4599537.5    NaN
           -4599512.5    NaN
           -4599487.5    NaN
           -4599462.5    NaN
           -4599437.5    NaN
           -4599412.5    NaN
           -4599387.5    NaN
           -4599362.5    NaN
           -4599337.5    NaN
           -4599312.5    NaN
           -4599287.5    NaN
           -4599262.5    NaN
                        ...
1099987.5  -4500737.5    NaN
           -4500712.5    NaN
           -4500687.5    NaN
           -4500662.5    NaN
           -4500637.5    NaN
           -4500612.5    NaN
           -4500587.5    NaN
           -4500562.5    NaN
           -4500537.5    NaN
           -4500512.5    NaN
           -4500487.5    NaN
           -4500462.5    NaN
           -4500437.5    NaN
           -4500412.5    NaN
           -4500387.5    NaN
           -4500362.5    NaN
           -4500337.5    NaN
           -4500312.5    NaN
           -4500287.5    NaN
           -4500262.5    NaN
           -4500237.5    NaN
           -4500212.5    NaN
           -4500187.5    NaN
           -4500162.5    NaN
           -4500137.5    NaN
           -4500112.5    NaN
           -4500087.5    NaN
           -4500062.5    NaN
           -4500037.5    NaN
           -4500012.5    NaN
Name: month, Length: 16000000, dtype: float64

In [13]:
attrs=bm.attrs

In [14]:
attrs

OrderedDict([('crs', 'EPSG:3577')])

In [15]:
month_xr = tempDF['month'].to_xarray()

In [16]:
print(month_xr)

<xarray.DataArray 'month' (x: 4000, y: 4000)>
array([[ 3., nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [ 3., nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * x        (x) float64 1e+06 1e+06 1e+06 1e+06 ... 1.1e+06 1.1e+06 1.1e+06
  * y        (y) float64 -4.6e+06 -4.6e+06 -4.6e+06 ... -4.5e+06 -4.5e+06

In [18]:
ds=xr.Dataset({'StartDate': (['y','x'], bm.StartDate),
               'StartMonth': (['x','y'], month_xr),
               'Duration': (['y','x'], bm.Duration), 
               'Severity': (['y','x'], bm.Severity), 
               'Severe': (['y','x'], bm.Severe),
               'Moderate': (['y','x'], bm.Moderate)},
                coords={'x': bm.x, 'y':bm.y}, attrs=bm.attrs)
"""
ds=xr.Dataset({'StartDate': (['y','x'], bm.StartDate),
               'StartMonth': (['y','x'], pd.DatetimeIndex(tempDF['StartDate']).month),
               'Duration': (['y','x'], bm.Duration), 
               'Severity': (['y','x'], bm.Severity), 
               'Severe': (['y','x'], bm.Severe),
               'Moderate': (['y','x'], bm.Moderate)},
                coords={'x': bm.x, 'y':bm.y}, attrs=bm.attrs)
"""

"\nds=xr.Dataset({'StartDate': (['y','x'], bm.StartDate),\n               'StartMonth': (['y','x'], pd.DatetimeIndex(tempDF['StartDate']).month),\n               'Duration': (['y','x'], bm.Duration), \n               'Severity': (['y','x'], bm.Severity), \n               'Severe': (['y','x'], bm.Severe),\n               'Moderate': (['y','x'], bm.Moderate)},\n                coords={'x': bm.x, 'y':bm.y}, attrs=bm.attrs)\n"

In [19]:
ds

<xarray.Dataset>
Dimensions:     (x: 4000, y: 4000)
Coordinates:
  * x           (x) float64 1e+06 1e+06 1e+06 1e+06 ... 1.1e+06 1.1e+06 1.1e+06
  * y           (y) float64 -4.6e+06 -4.6e+06 -4.6e+06 ... -4.5e+06 -4.5e+06
Data variables:
    StartDate   (y, x) float64 1.522e+18 nan 1.522e+18 nan ... nan nan nan nan
    StartMonth  (x, y) float64 3.0 nan nan nan nan nan ... nan nan nan nan nan
    Duration    (y, x) int16 63 0 63 0 0 0 0 31 31 0 0 ... 0 0 0 0 0 0 0 0 0 0 0
    Severity    (y, x) float32 2.0760202 0.0 1.6830531 0.0 ... 0.0 0.0 0.0 0.0
    Severe      (y, x) int8 1 0 1 0 0 0 0 1 1 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0
    Moderate    (y, x) int8 1 0 1 0 0 0 0 1 1 0 0 0 ... 0 0 0 0 0 0 0 0 0 0 0 0
Attributes:
    crs:      EPSG:3577

In [20]:
ds.to_netcdf('/g/data/r78/DPIPWE_lm/test_burn_mapping/output_data/2017_2018/BurnScarMap_2017_2018_13_-48_months.nc')